//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announce
    {
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public int AnnounceId { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool Force { get; set; }
        public bool Deleted { get; set; }
        public bool Enable { get; set; }
        public int UUId { get; set; }
        public string UUName { get; set; }
        public System.DateTime UDate { get; set; }
        public int CUId { get; set; }
        public string CUName { get; set; }
        public System.DateTime CDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Course Course { get; set; }
        public virtual Group Group { get; set; }
    }
}
