//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assignment()
        {
            this.AssignmentEnrollment = new HashSet<AssignmentEnrollment>();
            this.AssignmentTitle = new HashSet<AssignmentTitle>();
        }
    
        public int CourseId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public int AssignmentId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte UCount { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<int> FileId { get; set; }
        public byte Publish { get; set; }
        public bool Deleted { get; set; }
        public int CUId { get; set; }
        public string CUName { get; set; }
        public System.DateTime CDate { get; set; }
        public int UUId { get; set; }
        public System.DateTime UDate { get; set; }
        public string UName { get; set; }
    
        public virtual Course Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignmentEnrollment> AssignmentEnrollment { get; set; }
        public virtual Group Group { get; set; }
        public virtual AssignmentStats AssignmentStats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignmentTitle> AssignmentTitle { get; set; }
    }
}
