//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentStats
    {
        public int AssignmentId { get; set; }
        public int UploadCount { get; set; }
        public int RatedCount { get; set; }
        public int ViewCount { get; set; }
        public int EnrollCount { get; set; }
    
        public virtual Assignment Assignment { get; set; }
    }
}
