//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentEnrollment
    {
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public int UserId { get; set; }
        public int AssignmentId { get; set; }
        public int CEId { get; set; }
        public int EnrollmentId { get; set; }
        public byte Status { get; set; }
        public Nullable<int> Score { get; set; }
        public string ScoreDesc { get; set; }
        public int AttCount { get; set; }
        public Nullable<System.DateTime> AttFirst { get; set; }
        public Nullable<System.DateTime> AttLast { get; set; }
        public Nullable<int> FileId { get; set; }
    
        public virtual Assignment Assignment { get; set; }
        public virtual Course Course { get; set; }
        public virtual Enrollment Enrollment { get; set; }
        public virtual Group Group { get; set; }
        public virtual User User { get; set; }
    }
}
