//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanySetting
    {
        public int CompanyId { get; set; }
        public string GroupKey { get; set; }
        public string SettingKey { get; set; }
        public byte SettingType { get; set; }
        public string SettingValue { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
