//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentFileStats
    {
        public int FileId { get; set; }
        public int PublicCount { get; set; }
        public int EnrollCount { get; set; }
        public int ViewCount { get; set; }
        public System.DateTime FDate { get; set; }
    
        public virtual ContentFile ContentFile { get; set; }
    }
}
