//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentSession
    {
        public int ContentId { get; set; }
        public int UserId { get; set; }
        public int EnrollmentId { get; set; }
        public System.Guid SessionId { get; set; }
        public string SessionKey { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int PlayTime { get; set; }
        public int PlayTotal { get; set; }
        public int PlayLast { get; set; }
        public string PlayData { get; set; }
    
        public virtual Content Content { get; set; }
        public virtual ContentEnrollment ContentEnrollment { get; set; }
        public virtual User User { get; set; }
    }
}
