//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Control
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Control()
        {
            this.ControlCourse = new HashSet<ControlCourse>();
        }
    
        public int RequestId { get; set; }
        public string IdentityNo { get; set; }
        public string StudentNo { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public System.DateTime RDate { get; set; }
        public string RIP { get; set; }
        public int Status { get; set; }
        public string StatusText { get; set; }
        public string FacultyName { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> FacultyId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string CourseNames { get; set; }
        public bool Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlCourse> ControlCourse { get; set; }
    }
}
