//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentFile
    {
        public int CourseId { get; set; }
        public int TypeId { get; set; }
        public int FileId { get; set; }
        public Nullable<int> ContentId { get; set; }
        public string FileName { get; set; }
        public string FileNameO { get; set; }
        public Nullable<int> FileSize { get; set; }
        public string FileUrl { get; set; }
        public int Page { get; set; }
        public int Duration { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public bool Deleted { get; set; }
        public int CUId { get; set; }
        public string CUName { get; set; }
        public System.DateTime CDate { get; set; }
        public Nullable<int> UUId { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
        public string UUName { get; set; }
    
        public virtual ContentType ContentType { get; set; }
        public virtual ContentFileStats ContentFileStats { get; set; }
    }
}
