//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentEnrollment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContentEnrollment()
        {
            this.ContentSession = new HashSet<ContentSession>();
        }
    
        public int EnrollmentId { get; set; }
        public int ContentId { get; set; }
        public int UserId { get; set; }
        public System.DateTime AttFirst { get; set; }
        public System.DateTime AttLast { get; set; }
        public int AttCount { get; set; }
        public string ScoreData { get; set; }
        public int GroupId { get; set; }
        public byte Status { get; set; }
        public int CourseId { get; set; }
        public int Score { get; set; }
        public int CEId { get; set; }
        public string PlayData { get; set; }
        public int ScorePercent { get; set; }
        public int PlayTime { get; set; }
        public int PlayTotal { get; set; }
        public int PlayLast { get; set; }
    
        public virtual Content Content { get; set; }
        public virtual Course Course { get; set; }
        public virtual Enrollment Enrollment { get; set; }
        public virtual Group Group { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContentSession> ContentSession { get; set; }
    }
}
