//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Content()
        {
            this.ContentEnrollment = new HashSet<ContentEnrollment>();
            this.ContentSession = new HashSet<ContentSession>();
        }
    
        public int CourseId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> ContainerId { get; set; }
        public int TypeId { get; set; }
        public int ContentId { get; set; }
        public int ContentIndex { get; set; }
        public string Name { get; set; }
        public Nullable<int> FileId { get; set; }
        public string Url { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Heigth { get; set; }
        public int Duration { get; set; }
        public int Page { get; set; }
        public byte Publish { get; set; }
        public bool Deleted { get; set; }
        public bool Tracking { get; set; }
        public int CUId { get; set; }
        public string CUName { get; set; }
        public System.DateTime CDate { get; set; }
        public int UUId { get; set; }
        public System.DateTime UDate { get; set; }
        public string UUName { get; set; }
        public Nullable<int> ImportKey { get; set; }
    
        public virtual Container Container { get; set; }
        public virtual ContentType ContentType { get; set; }
        public virtual Course Course { get; set; }
        public virtual Group Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContentEnrollment> ContentEnrollment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContentSession> ContentSession { get; set; }
        public virtual ContentStats ContentStats { get; set; }
    }
}
