//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlCourse
    {
        public int RequestId { get; set; }
        public int CourseId { get; set; }
        public string CourseName { get; set; }
        public int Status { get; set; }
        public string StatusText { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Control Control { get; set; }
    }
}
