//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContentType()
        {
            this.Content = new HashSet<Content>();
            this.ContentFile = new HashSet<ContentFile>();
        }
    
        public int TypeGroup { get; set; }
        public int TypeId { get; set; }
        public string Name { get; set; }
        public string Icon { get; set; }
        public bool Tracking { get; set; }
        public string Title { get; set; }
        public string Embed { get; set; }
        public bool Progress { get; set; }
        public string ProgressFormat { get; set; }
        public string AttFormat { get; set; }
        public bool AttTime { get; set; }
        public string Extensions { get; set; }
        public bool Upload { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Content> Content { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContentFile> ContentFile { get; set; }
    }
}
