//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Assignment = new HashSet<Assignment>();
            this.AssignmentEnrollment = new HashSet<AssignmentEnrollment>();
            this.Content = new HashSet<Content>();
            this.ContentEnrollment = new HashSet<ContentEnrollment>();
            this.Announce = new HashSet<Announce>();
            this.ControlCourse = new HashSet<ControlCourse>();
            this.Enrollment = new HashSet<Enrollment>();
            this.Exam = new HashSet<Exam>();
            this.ExamEnrollment = new HashSet<ExamEnrollment>();
            this.Group = new HashSet<Group>();
            this.SyncItem = new HashSet<SyncItem>();
            this.VClass = new HashSet<VClass>();
            this.VClassSchedule = new HashSet<VClassSchedule>();
        }
    
        public int CompanyId { get; set; }
        public int UnitId { get; set; }
        public int CourseId { get; set; }
        public string ImportKey { get; set; }
        public System.Guid UniqueKey { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int EType { get; set; }
        public int CMode { get; set; }
        public int CType { get; set; }
        public bool Enable { get; set; }
        public bool Paid { get; set; }
        public bool Deleted { get; set; }
        public int CUId { get; set; }
        public System.DateTime CDate { get; set; }
        public string CUName { get; set; }
        public int UUId { get; set; }
        public System.DateTime UDate { get; set; }
        public string UUName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assignment> Assignment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignmentEnrollment> AssignmentEnrollment { get; set; }
        public virtual Company Company { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Content> Content { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContentEnrollment> ContentEnrollment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Announce> Announce { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlCourse> ControlCourse { get; set; }
        public virtual CourseSettings CourseSettings { get; set; }
        public virtual CourseStats CourseStats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrollment> Enrollment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam> Exam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamEnrollment> ExamEnrollment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group> Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SyncItem> SyncItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VClass> VClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VClassSchedule> VClassSchedule { get; set; }
    }
}
