//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseSales
    {
        public int CourseId { get; set; }
        public string Title { get; set; }
        public decimal Price { get; set; }
        public string PhotoUrl { get; set; }
        public string Contact { get; set; }
        public bool Enable { get; set; }
        public Nullable<System.DateTime> AdmissionStartDate { get; set; }
        public Nullable<System.DateTime> AdmissionEndDate { get; set; }
        public string AdmissionDesc { get; set; }
        public string AdmissionConditions { get; set; }
        public Nullable<System.DateTime> CourseStartDate { get; set; }
        public Nullable<System.DateTime> CourseEndDate { get; set; }
        public Nullable<int> CourseHour { get; set; }
        public string CourseTitles { get; set; }
        public string CourseDesc { get; set; }
        public Nullable<System.DateTime> ExamStartDate { get; set; }
        public Nullable<System.DateTime> ExamEndDate { get; set; }
        public string ExamDesc { get; set; }
    }
}
