//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data
    {
        public int StatsId { get; set; }
        public int StatsType { get; set; }
        public int Unit { get; set; }
        public int User { get; set; }
        public int Manager { get; set; }
        public int Template { get; set; }
        public int Course { get; set; }
        public int Group { get; set; }
        public int Enrollment { get; set; }
    }
}
