//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Enrollment()
        {
            this.AssignmentEnrollment = new HashSet<AssignmentEnrollment>();
            this.ContentEnrollment = new HashSet<ContentEnrollment>();
            this.ExamEnrollment = new HashSet<ExamEnrollment>();
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int CourseId { get; set; }
        public int GroupId { get; set; }
        public int UserId { get; set; }
        public int EnrollmentId { get; set; }
        public System.Guid EnrollKey { get; set; }
        public bool Canceled { get; set; }
        public bool Completed { get; set; }
        public System.DateTime EnrollDate { get; set; }
        public decimal Score { get; set; }
        public bool Control { get; set; }
        public decimal Payment { get; set; }
        public bool PaymentConfirm { get; set; }
        public decimal Price { get; set; }
        public int CUId { get; set; }
        public System.DateTime CDate { get; set; }
        public bool Active { get; set; }
        public Nullable<int> SyncId { get; set; }
        public Nullable<int> LessonId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignmentEnrollment> AssignmentEnrollment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContentEnrollment> ContentEnrollment { get; set; }
        public virtual Course Course { get; set; }
        public virtual Group Group { get; set; }
        public virtual Lesson Lesson { get; set; }
        public virtual SyncItem SyncItem { get; set; }
        public virtual User User { get; set; }
        public virtual EnrollmentStats EnrollmentStats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamEnrollment> ExamEnrollment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
