//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrollmentStats
    {
        public int EnrolmentId { get; set; }
        public int EnrollPercent { get; set; }
    
        public virtual Enrollment Enrollment { get; set; }
    }
}
