//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exam()
        {
            this.ExamAnswer = new HashSet<ExamAnswer>();
            this.ExamEnrollment = new HashSet<ExamEnrollment>();
            this.ExamQuestion = new HashSet<ExamQuestion>();
            this.ExamSession = new HashSet<ExamSession>();
            this.ExamTitles = new HashSet<ExamTitles>();
        }
    
        public int CourseId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public int ExamId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public int Duration { get; set; }
        public int QCount { get; set; }
        public int QVCount { get; set; }
        public byte Publish { get; set; }
        public bool Deleted { get; set; }
        public int CUId { get; set; }
        public System.DateTime CDate { get; set; }
        public string CUName { get; set; }
        public Nullable<int> UUId { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
        public string UUName { get; set; }
        public Nullable<System.DateTime> DateShow { get; set; }
        public bool QShow { get; set; }
        public bool QAShow { get; set; }
        public Nullable<decimal> ScorePass { get; set; }
        public int AttMax { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Group Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamAnswer> ExamAnswer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamEnrollment> ExamEnrollment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamQuestion> ExamQuestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamSession> ExamSession { get; set; }
        public virtual ExamStats ExamStats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamTitles> ExamTitles { get; set; }
    }
}
