//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamQuestionStats
    {
        public int QuestionId { get; set; }
        public int SRCount { get; set; }
        public int SWCount { get; set; }
        public int SVCount { get; set; }
    
        public virtual ExamQuestion ExamQuestion { get; set; }
    }
}
