//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamStats
    {
        public int ExamId { get; set; }
        public int SessionCount { get; set; }
        public int EnrollCount { get; set; }
        public decimal ScoreAvg { get; set; }
        public decimal ScoreMax { get; set; }
        public int EnrollActive { get; set; }
        public int EnrollTotal { get; set; }
        public int AttCount { get; set; }
        public int AttTotal { get; set; }
    
        public virtual Exam Exam { get; set; }
    }
}
