//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamSession
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamSession()
        {
            this.ExamAnswer = new HashSet<ExamAnswer>();
        }
    
        public int ExamId { get; set; }
        public int UserId { get; set; }
        public int CEId { get; set; }
        public int EnrollmentId { get; set; }
        public int SessionId { get; set; }
        public byte Status { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool EndAuto { get; set; }
        public byte EndType { get; set; }
        public int QCount { get; set; }
        public int RCount { get; set; }
        public int WCount { get; set; }
        public decimal Score { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Exam Exam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamAnswer> ExamAnswer { get; set; }
        public virtual ExamEnrollment ExamEnrollment { get; set; }
    }
}
