//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faq
    {
        public int CompanyId { get; set; }
        public int CategoryId { get; set; }
        public int FaqId { get; set; }
        public int FaqIndex { get; set; }
        public string Question { get; set; }
        public string Description { get; set; }
        public string Icon { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
