//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lesson()
        {
            this.Enrollment = new HashSet<Enrollment>();
            this.SyncItem = new HashSet<SyncItem>();
        }
    
        public int CompanyId { get; set; }
        public int FacultyId { get; set; }
        public int DepartmentId { get; set; }
        public int LessonId { get; set; }
        public string LessonCode { get; set; }
        public string LessonName { get; set; }
        public string ImportKey { get; set; }
        public System.Guid UniqueKey { get; set; }
        public int CountStudent { get; set; }
        public bool Ignored { get; set; }
        public int CUId { get; set; }
        public System.DateTime CDate { get; set; }
        public string CUName { get; set; }
        public int UUId { get; set; }
        public System.DateTime UDate { get; set; }
        public string UUName { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<System.DateTime> MapDate { get; set; }
        public Nullable<int> MapUId { get; set; }
        public string MapUser { get; set; }
        public bool Checked { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrollment> Enrollment { get; set; }
        public virtual Group Group { get; set; }
        public virtual Department Department { get; set; }
        public virtual Faculty Faculty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SyncItem> SyncItem { get; set; }
    }
}
