//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Limit
    {
        public int CompanyId { get; set; }
        public int CourseLimit { get; set; }
        public int UserLimit { get; set; }
        public int ContentLimit { get; set; }
        public int ExamLimit { get; set; }
        public int VClassLimit { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
