//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int CompanyId { get; set; }
        public int LoginId { get; set; }
        public string UserName { get; set; }
        public string TryPass { get; set; }
        public string IP { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> UserId { get; set; }
        public int Status { get; set; }
        public string SessionID { get; set; }
        public string Url { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual User User { get; set; }
    }
}
