//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mail
    {
        public int TemplateId { get; set; }
        public int MailId { get; set; }
        public string UserFrom { get; set; }
        public string UserTo { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public System.Guid SenderId { get; set; }
        public bool Sended { get; set; }
        public string SendedMessage { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public bool WebRead { get; set; }
        public Nullable<System.DateTime> WebReadDate { get; set; }
    
        public virtual MailTemplate MailTemplate { get; set; }
    }
}
