//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailTemplate
    {
        public int TemplateId { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public bool Deleted { get; set; }
        public int CUId { get; set; }
        public System.DateTime CDate { get; set; }
        public string CUName { get; set; }
        public System.DateTime UDate { get; set; }
        public int UUId { get; set; }
        public string UUName { get; set; }
    
        public virtual Mail Mail { get; set; }
    }
}
