//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TLMSPortalEntity : DbContext
    {
        public TLMSPortalEntity()
            : base("name=TLMSPortalEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<ColorSet> ColorSet { get; set; }
        public virtual DbSet<Mail> Mail { get; set; }
        public virtual DbSet<MailTemplate> MailTemplate { get; set; }
        public virtual DbSet<Resource> Resource { get; set; }
        public virtual DbSet<Setting> Setting { get; set; }
        public virtual DbSet<Assignment> Assignment { get; set; }
        public virtual DbSet<AssignmentDates> AssignmentDates { get; set; }
        public virtual DbSet<AssignmentEnrollment> AssignmentEnrollment { get; set; }
        public virtual DbSet<AssignmentFiles> AssignmentFiles { get; set; }
        public virtual DbSet<AssignmentStats> AssignmentStats { get; set; }
        public virtual DbSet<AssignmentTitle> AssignmentTitle { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<CompanySetting> CompanySetting { get; set; }
        public virtual DbSet<CompanyStats> CompanyStats { get; set; }
        public virtual DbSet<Host> Host { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<Limit> Limit { get; set; }
        public virtual DbSet<Price> Price { get; set; }
        public virtual DbSet<Social> Social { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<UnitManager> UnitManager { get; set; }
        public virtual DbSet<UnitStats> UnitStats { get; set; }
        public virtual DbSet<UnitTerms> UnitTerms { get; set; }
        public virtual DbSet<UnitTitles> UnitTitles { get; set; }
        public virtual DbSet<Content> Content { get; set; }
        public virtual DbSet<ContentEnrollment> ContentEnrollment { get; set; }
        public virtual DbSet<ContentFile> ContentFile { get; set; }
        public virtual DbSet<ContentFileStats> ContentFileStats { get; set; }
        public virtual DbSet<ContentSession> ContentSession { get; set; }
        public virtual DbSet<ContentStats> ContentStats { get; set; }
        public virtual DbSet<ContentTitles> ContentTitles { get; set; }
        public virtual DbSet<ContentType> ContentType { get; set; }
        public virtual DbSet<Link> Link { get; set; }
        public virtual DbSet<Container> Container { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<CourseSales> CourseSales { get; set; }
        public virtual DbSet<CourseSettings> CourseSettings { get; set; }
        public virtual DbSet<CourseStats> CourseStats { get; set; }
        public virtual DbSet<Enrollment> Enrollment { get; set; }
        public virtual DbSet<EnrollmentStats> EnrollmentStats { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<GroupStats> GroupStats { get; set; }
        public virtual DbSet<GroupTeacher> GroupTeacher { get; set; }
        public virtual DbSet<Title> Title { get; set; }
        public virtual DbSet<Exam> Exam { get; set; }
        public virtual DbSet<ExamAnswer> ExamAnswer { get; set; }
        public virtual DbSet<ExamDates> ExamDates { get; set; }
        public virtual DbSet<ExamEnrollment> ExamEnrollment { get; set; }
        public virtual DbSet<ExamQuestion> ExamQuestion { get; set; }
        public virtual DbSet<ExamQuestionStats> ExamQuestionStats { get; set; }
        public virtual DbSet<ExamQuestionTitles> ExamQuestionTitles { get; set; }
        public virtual DbSet<ExamSession> ExamSession { get; set; }
        public virtual DbSet<ExamStats> ExamStats { get; set; }
        public virtual DbSet<ExamTitles> ExamTitles { get; set; }
        public virtual DbSet<Faq> Faq { get; set; }
        public virtual DbSet<SupportCategory> SupportCategory { get; set; }
        public virtual DbSet<SupportTitle> SupportTitle { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<TicketAction> TicketAction { get; set; }
        public virtual DbSet<TicketMessage> TicketMessage { get; set; }
        public virtual DbSet<Announce> Announce { get; set; }
        public virtual DbSet<Data> Data { get; set; }
        public virtual DbSet<Days> Days { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<ReportCategory> ReportCategory { get; set; }
        public virtual DbSet<ReportQuery> ReportQuery { get; set; }
        public virtual DbSet<Calendar> Calendar { get; set; }
        public virtual DbSet<Control> Control { get; set; }
        public virtual DbSet<ControlCourse> ControlCourse { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Faculty> Faculty { get; set; }
        public virtual DbSet<Lesson> Lesson { get; set; }
        public virtual DbSet<SyncItem> SyncItem { get; set; }
        public virtual DbSet<SyncLog> SyncLog { get; set; }
        public virtual DbSet<Term> Term { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserClaims> UserClaims { get; set; }
        public virtual DbSet<UserDevice> UserDevice { get; set; }
        public virtual DbSet<UserInvoice> UserInvoice { get; set; }
        public virtual DbSet<UserLogins> UserLogins { get; set; }
        public virtual DbSet<UserPermissions> UserPermissions { get; set; }
        public virtual DbSet<UserSimulates> UserSimulates { get; set; }
        public virtual DbSet<UserStats> UserStats { get; set; }
        public virtual DbSet<VClass> VClass { get; set; }
        public virtual DbSet<VClassEnrollment> VClassEnrollment { get; set; }
        public virtual DbSet<VClassEnrollment_Bak> VClassEnrollment_Bak { get; set; }
        public virtual DbSet<VClassProvider> VClassProvider { get; set; }
        public virtual DbSet<VClassSchedule> VClassSchedule { get; set; }
        public virtual DbSet<VClassStats> VClassStats { get; set; }
        public virtual DbSet<VClassTitles> VClassTitles { get; set; }
    }
}
