//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int CompanyId { get; set; }
        public int Interval { get; set; }
        public decimal Price1 { get; set; }
        public int Start { get; set; }
        public int End { get; set; }
    }
}
