//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ReportId { get; set; }
        public string Title { get; set; }
        public bool Total { get; set; }
        public bool University { get; set; }
        public bool Edudation { get; set; }
        public bool FacultyUnit { get; set; }
        public bool DepartmentUnit { get; set; }
        public bool Course { get; set; }
        public bool Group { get; set; }
        public bool Activity { get; set; }
    }
}
