//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.Payment = new HashSet<Payment>();
            this.UserInvoice = new HashSet<UserInvoice>();
        }
    
        public int CompanyId { get; set; }
        public Nullable<int> UserId { get; set; }
        public int RequestId { get; set; }
        public string IdentityNo { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int BirthYear { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public int CityId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string DistrictName { get; set; }
        public string Adress { get; set; }
        public Nullable<int> Status { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public bool Called { get; set; }
        public bool Enable { get; set; }
        public int CourseId { get; set; }
        public int GroupId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
        public virtual Payment Payment1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserInvoice> UserInvoice { get; set; }
        public virtual UserInvoice UserInvoice1 { get; set; }
        public virtual User User { get; set; }
    }
}
