//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SyncItem()
        {
            this.Enrollment = new HashSet<Enrollment>();
            this.SyncLog = new HashSet<SyncLog>();
        }
    
        public int SyncId { get; set; }
        public System.DateTime SyncDate { get; set; }
        public string SyncUser { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> LessonId { get; set; }
        public string FileUrl { get; set; }
        public string FileName { get; set; }
        public int AddedStudent { get; set; }
        public int UpdatedStudent { get; set; }
        public int DeletedStudent { get; set; }
        public int AddedTeacher { get; set; }
        public int UpdatedTeacher { get; set; }
        public int DeletedTeacher { get; set; }
        public int AddedGroup { get; set; }
        public int UpdatedGroup { get; set; }
        public int DeletedGroup { get; set; }
    
        public virtual Unit Unit { get; set; }
        public virtual Course Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrollment> Enrollment { get; set; }
        public virtual Group Group { get; set; }
        public virtual Lesson Lesson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SyncLog> SyncLog { get; set; }
    }
}
