//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncLog
    {
        public int LogId { get; set; }
        public int SyncId { get; set; }
        public string LogData { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> LessonId { get; set; }
        public int UserKey { get; set; }
    
        public virtual SyncItem SyncItem { get; set; }
    }
}
