//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Term
    {
        public int CompanyId { get; set; }
        public int CalendarId { get; set; }
        public int TermId { get; set; }
        public int TermYear { get; set; }
        public int Term1 { get; set; }
        public string TermName { get; set; }
        public string ImportKey { get; set; }
        public System.Guid UniqueKey { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int CUId { get; set; }
        public System.DateTime CDate { get; set; }
        public string CUName { get; set; }
        public int UUId { get; set; }
        public System.DateTime UDate { get; set; }
        public string UUName { get; set; }
    }
}
