//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.TicketAction = new HashSet<TicketAction>();
            this.TicketMessage = new HashSet<TicketMessage>();
        }
    
        public int UserId { get; set; }
        public int TitleId { get; set; }
        public int TicketId { get; set; }
        public System.DateTime TicketDate { get; set; }
        public string Description { get; set; }
        public string Screenshot { get; set; }
        public int Status { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> EnrollmentId { get; set; }
    
        public virtual Enrollment Enrollment { get; set; }
        public virtual SupportTitle SupportTitle { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketAction> TicketAction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketMessage> TicketMessage { get; set; }
    }
}
