//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketAction
    {
        public Nullable<int> TicketId { get; set; }
        public int ActionId { get; set; }
        public string ActionTitle { get; set; }
        public System.DateTime ActionDate { get; set; }
        public string ActionUser { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
