//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitManager
    {
        public int UnitId { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
    
        public virtual Unit Unit { get; set; }
    }
}
