//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitTerms
    {
        public int UnitId { get; set; }
        public int TermId { get; set; }
        public int TermIndex { get; set; }
        public string TermName { get; set; }
        public int TermYear { get; set; }
        public string TermTheme { get; set; }
    }
}
