//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitTitles
    {
        public int UnitId { get; set; }
        public byte LanguageId { get; set; }
        public int TitleId { get; set; }
        public int TitleNo { get; set; }
        public string Description { get; set; }
        public short Year { get; set; }
    }
}
