//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPermissions
    {
        public string UserName { get; set; }
        public int UserId { get; set; }
        public bool Support { get; set; }
        public bool Simulate { get; set; }
        public bool Report { get; set; }
        public bool Trace { get; set; }
        public bool Portal { get; set; }
        public int CUId { get; set; }
        public System.DateTime CDate { get; set; }
        public int UUId { get; set; }
        public System.DateTime UDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
