//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSimulates
    {
        public int SId { get; set; }
        public System.Guid TicketId { get; set; }
        public int UserId { get; set; }
        public System.DateTime SDate { get; set; }
        public System.DateTime EDate { get; set; }
        public string UName { get; set; }
        public string TURole { get; set; }
        public string TUName { get; set; }
    
        public virtual User User { get; set; }
    }
}
