//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInvoice()
        {
            this.Request1 = new HashSet<Request>();
        }
    
        public int RequestId { get; set; }
        public int CourseId { get; set; }
        public int GroupId { get; set; }
        public int UserId { get; set; }
        public int UserInvoiceId { get; set; }
        public string No { get; set; }
        public System.DateTime Date { get; set; }
        public string Data { get; set; }
        public bool Printed { get; set; }
    
        public virtual Request Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Request1 { get; set; }
        public virtual User User { get; set; }
    }
}
