//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VClassProvider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VClassProvider()
        {
            this.VClass = new HashSet<VClass>();
            this.Company = new HashSet<Company>();
        }
    
        public int ProviderId { get; set; }
        public byte Type { get; set; }
        public byte Order { get; set; }
        public string Data { get; set; }
        public string Name { get; set; }
        public bool Enable { get; set; }
        public bool Shared { get; set; }
        public bool Frame { get; set; }
        public int CUId { get; set; }
        public System.DateTime CDate { get; set; }
        public int UUId { get; set; }
        public System.DateTime UDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VClass> VClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company> Company { get; set; }
    }
}
