//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToltekLMSPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VClass()
        {
            this.VClassTitles = new HashSet<VClassTitles>();
        }
    
        public int ProviderId { get; set; }
        public int CourseId { get; set; }
        public int VClassId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> ContainerId { get; set; }
        public Nullable<int> ScheduleId { get; set; }
        public Nullable<int> ImportKey { get; set; }
        public int ContentIndex { get; set; }
        public string Url { get; set; }
        public string Name { get; set; }
        public bool Replay { get; set; }
        public System.DateTime StartDate { get; set; }
        public int Duration { get; set; }
        public bool Packaged { get; set; }
        public byte Publish { get; set; }
        public bool Deleted { get; set; }
        public int CUId { get; set; }
        public System.DateTime CDate { get; set; }
        public string CUName { get; set; }
        public int UUId { get; set; }
        public System.DateTime UDate { get; set; }
        public string UUName { get; set; }
    
        public virtual Container Container { get; set; }
        public virtual Course Course { get; set; }
        public virtual Group Group { get; set; }
        public virtual VClassProvider VClassProvider { get; set; }
        public virtual VClassSchedule VClassSchedule { get; set; }
        public virtual VClassStats VClassStats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VClassTitles> VClassTitles { get; set; }
    }
}
